-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd [[highlight clear]]

local highlight = function(group, bg, fg, attr)
  fg = fg and 'guifg=' .. fg or ''
  bg = bg and 'guibg=' .. bg or ''
  attr = attr and 'gui=' .. attr or ''

  vim.api.nvim_command('highlight ' .. group .. ' ' .. fg .. ' ' .. bg .. ' ' .. attr)
end

local link = function(target, group)
  vim.api.nvim_command('highlight! link ' .. target .. ' ' .. group)
end

local Color1 = '#EBCB8B'
local Color8 = '#1e2127'
local Color2 = '#B48EAD'
local Color9 = '#7b88a1'
local Color0 = '#616d87'
local Color3 = '#88C0D0'
local Color12 = '#343a48'
local Color6 = '#4b5163'
local Color7 = '#191c22'
local Color4 = '#81A1C1'
local Color11 = '#33292f'
local Color5 = '#A3BE8C'
local Color13 = '#4c566a'
local Color10 = '#2f3534'
local Color14 = '#d8dee9'

highlight('Comment', nil, Color0, 'italic')
highlight('TSCharacter', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Operator', nil, Color4, nil)
highlight('Type', nil, Color4, nil)
highlight('String', nil, Color5, nil)
highlight('StatusLine', Color6, Color7, nil)
highlight('WildMenu', Color8, Color9, nil)
highlight('Pmenu', Color8, Color9, nil)
highlight('PmenuSel', Color9, Color8, nil)
highlight('PmenuThumb', Color8, Color9, nil)
highlight('DiffAdd', Color10, nil, nil)
highlight('DiffDelete', Color11, nil, nil)
highlight('Normal', Color8, Color9, nil)
highlight('NormalFloat', Color8, Color9, nil)
highlight('Visual', Color12, nil, nil)
highlight('CursorLine', Color12, nil, nil)
highlight('ColorColumn', Color12, nil, nil)
highlight('SignColumn', Color8, nil, nil)
highlight('LineNr', nil, Color13, nil)
highlight('TabLine', Color7, Color6, nil)
highlight('TabLineSel', Color14, Color8, nil)
highlight('TabLineFill', Color7, Color6, nil)
highlight('TSPunctDelimiter', nil, Color9, nil)

link('TSLabel', 'Type')
link('TSProperty', 'TSField')
link('TSFunction', 'Function')
link('TSFloat', 'Number')
link('Operator', 'Keyword')
link('TelescopeNormal', 'Normal')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSFuncMacro', 'Macro')
link('CursorLineNr', 'Identifier')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSType', 'Type')
link('Whitespace', 'Comment')
link('TSConstant', 'Constant')
link('TSTagDelimiter', 'Type')
link('Macro', 'Function')
link('NonText', 'Comment')
link('TSConditional', 'Conditional')
link('TSParameter', 'Constant')
link('TSOperator', 'Operator')
link('TSString', 'String')
link('TSTag', 'MyTag')
link('TSRepeat', 'Repeat')
link('TSPunctBracket', 'MyTag')
link('Repeat', 'Conditional')
link('Folded', 'Comment')
link('TSNamespace', 'TSType')
link('TSField', 'Constant')
link('TSComment', 'Comment')
link('TSParameterReference', 'TSParameter')
link('TSNumber', 'Number')
link('Conditional', 'Operator')
link('TSKeyword', 'Keyword')
